// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwis_ZfNlAyihALYEfkERn_8hsZWVdYXA',
    appId: '1:413817509461:android:85cb4c87ac4b0dedc926dc',
    messagingSenderId: '413817509461',
    projectId: 'ashry-81eaa',
    databaseURL: 'https://ashry-81eaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ashry-81eaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXlvhiyCTtY-4ZcBT2a-0FFM4j6zA_a8k',
    appId: '1:413817509461:ios:cead3528c61fab39c926dc',
    messagingSenderId: '413817509461',
    projectId: 'ashry-81eaa',
    databaseURL: 'https://ashry-81eaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ashry-81eaa.appspot.com',
    androidClientId: '413817509461-374q6jm1fgfd2ac3gjklvmob7a82aesl.apps.googleusercontent.com',
    iosClientId: '413817509461-2hea5430gme95pu9tr0itgjo3q23oleq.apps.googleusercontent.com',
    iosBundleId: 'com.ashryupp.app',
  );
}
